# Site settings
title: "Fall-Back"
email: "andy.kirk@gridlight-design.co.uk"
description: "Accessible, Progressive Enhancement patterns."
repository: "Fall-Back/Fall-Back.github.io"
baseurl: ""
url: "http://fall-back.github.io/"
port: 4001

# Build settings
markdown: kramdown


kramdown:
  auto_ids:       true

  
  
exclude: [
    "_archive",
    "bower.json", 
    "bower_components",
    "Gemfile",
    "Gemfile.lock",
    "Gruntfile.js",
    "local-grunt.bat",
    "local-jekyll.bat",
    "node_modules", 
    "package.json",
    "README.md"
]
