# Site settings
title: "NPEU Mockups"
email: "andy.kirk@npeu.ox.ac.uk"
description: "Testing things out"
repository: "https://github.com/NPEU/mockups"
baseurl: ""
url: "https://lab.npeu.ox.ac.uk/mockup/"
port: 4001


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      is_home: false
      headline_image: false

# Build settings
markdown: kramdown


kramdown:
  auto_ids:       true

  
  
exclude: [
    "_archive",
    "bower.json", 
    "bower_components",
    "Gemfile",
    "Gemfile.lock",
    "Gruntfile.js",
    "gulpfile.js",
    "local-grunt.bat",
    "local-gulp.bat",
    "local-jekyll.bat",
    "node_modules", 
    "package.json",
    "package-bk.json",
    "README.md"
]
