# Site settings
title: "NPEU Mockups"
email: "andy.kirk@npeu.ox.ac.uk"
description: "Testing things out"
repository: "https://github.com/NPEU/mockups"
baseurl: ""
url: "https://lab.npeu.ox.ac.uk/mockup/"
port: 4001


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      display_cta: true
      display_funder: true
      display_hero: true
      display_navbar: true
      display_social: true
      display_support: true
      is_home: false
      headline_image: true
      landing_brochure: false
      landing_display_cta: true
      landing_display_info: true
      landing_display_signpost_bottom: true
      landing_display_signpost_top: true
      landing_display_updates: true
      landing_display_video: true
      layout_name: "default"
      npeu_unit: false
      section_menu: false
      toc: false
      has_pull_outs: false
      had_map: false

# Build settings
markdown: kramdown

kramdown:
  auto_ids:       true



exclude: [
    "_archive",
    "bower.json",
    "bower_components",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "local-gulp.bat",
    "local-jekyll.bat",
    "node_modules",
    "package.json",
    "README.md"
]
